FROM node:22-slim

WORKDIR /app

COPY package.json ./

# Garantir que todas as dependências sejam instaladas (incluindo devDependencies)
ENV NODE_ENV=development
RUN npm install

COPY . .

# Adicionar node_modules/.bin ao PATH
ENV PATH="/app/node_modules/.bin:${PATH}"

EXPOSE 5000

CMD ["npm", "run", "start:dev"]