obelisk-backend-node:
  image: obelisk-backend-node:latest
  build:
    context: ./node/backend-node
    dockerfile: Dockerfile
  container_name: obelisk-backend-node
  environment:
    - NODE_ENV=development
    - PORT=5000
    - DATABASE_URL=postgresql://root@cockroach:26257/defaultdb?sslmode=disable
    - DB_HOST=cockroach
    - DB_PORT=26257
    - DB_NAME=defaultdb
    - DB_USER=root
    - DB_SSL=false
    - REDIS_HOST=valkey
    - REDIS_PORT=6379
    - REDIS_DATABASE=0
    - REDIS_KEY_PREFIX=backend-node:
    - REDIS_USE_TLS=false
    - THIRDWEB_SECRET_KEY=dev-secret-key
    - THIRDWEB_CLIENT_ID=dev-client-id
    - THIRDWEB_AUTH_DOMAIN=localhost:5000
    - AWS_REGION=us-east-1
    - AWS_EVENTBRIDGE_BUS_NAME=dev-events
    - AWS_EVENTBRIDGE_SOURCE=illuvium.backend.node
  ports:
    - '5000:5000'
  depends_on:
    - cockroach
    - valkey
  networks:
    - obelisk
