services:
  backend-node:
    image: backend-node-test:slim
    container_name: backend-node-test
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://root@illuvium-cockroachdb:26257/illuvium?sslmode=disable
      DB_HOST: illuvium-cockroachdb
      DB_PORT: 26257
      DB_NAME: illuvium
      DB_USER: root
      DB_PASSWORD: ''
      DB_SSL: 'false'
      REDIS_HOST: illuvium-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      REDIS_DATABASE: 0
      REDIS_KEY_PREFIX: 'backend-node:'
      REDIS_USE_TLS: 'false'
      THIRDWEB_SECRET_KEY: test-secret-key
      THIRDWEB_CLIENT_ID: test-client-id
      THIRDWEB_AUTH_DOMAIN: localhost:5000
      AWS_REGION: us-east-1
      AWS_EVENTBRIDGE_BUS_NAME: illuvium-events
      AWS_EVENTBRIDGE_SOURCE: illuvium.backend.node
      OTEL_SERVICE_NAME: backend-node
      OTEL_SERVICE_VERSION: '1.0.0'
      OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318/v1/traces
      RATE_LIMIT_TTL: 60
      RATE_LIMIT_MAX: 100
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5000
    depends_on:
      - illuvium-cockroachdb
      - illuvium-redis
    networks:
      - backend-node_illuvium-network
    external_links:
      - illuvium-cockroachdb
      - illuvium-redis

networks:
  backend-node_illuvium-network:
    external: true