export const ASSET_REPOSITORY = 'ASSET_REPOSITORY';

export const BLOCKCHAIN_CONTRACT_REPOSITORY = 'BLOCKCHAIN_CONTRACT_REPOSITORY';
export const BLOCKCHAIN_ASSET_REPOSITORY = 'BLOCKCHAIN_ASSET_REPOSITORY';
export const ASSET_TRANSACTION_REPOSITORY = 'ASSET_TRANSACTION_REPOSITORY';
export const ASSET_MARKETPLACE_REPOSITORY = 'ASSET_MARKETPLACE_REPOSITORY';
