import { Generated, Selectable, Insertable, Updateable } from 'kysely';

/**
 * Interfaces that define the database structure for Kysely
 */

/**
 * Interface for the 'assets' table
 */
export interface AssetTable {
  id: Generated<string>; // UUID generated by the database
  name: string;
  description: string;
  image_url: string; // Uses snake_case in the database
  price: number;
  tags: string[]; // Array of tags
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/**
 * Main database interface, containing all tables
 */
export interface Database {
  assets: AssetTable;
  // Add other tables here as needed
}

/**
 * Helper types to facilitate selection, insertion, and update operations
 */
export type Asset = Selectable<AssetTable>;
export type NewAsset = Insertable<AssetTable>;
export type AssetUpdate = Updateable<AssetTable>;
