import { Generated, Selectable, Insertable, Updateable } from 'kysely';

/**
 * Interfaces that define the database structure for Kysely
 */

/**
 * Interface for the 'assets' table
 */
export interface AssetTable {
  id: Generated<string>; // UUID generated by the database
  name: string;
  description: string;
  image_url: string; // Uses snake_case in the database
  price: number;
  tags: string[]; // Array of tags
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/**
 * Interface for the 'users' table
 */
export interface UserTable {
  id: Generated<string>; // UUID generated by the database
  privy_id: string; // Unique Privy user identifier
  wallet_address: string | null; // User's wallet address
  email: string | null; // User's email
  phone_number: string | null; // User's phone number
  is_active: Generated<boolean>; // Whether the user is active
  created_at: Generated<Date>;
  updated_at: Generated<Date>;
}

/**
 * Main database interface, containing all tables
 */
export interface Database {
  assets: AssetTable;
  users: UserTable;
  // Add other tables here as needed
}

/**
 * Helper types to facilitate selection, insertion, and update operations
 */
export type Asset = Selectable<AssetTable>;
export type NewAsset = Insertable<AssetTable>;
export type AssetUpdate = Updateable<AssetTable>;

export type User = Selectable<UserTable>;
export type NewUser = Insertable<UserTable>;
export type UserUpdate = Updateable<UserTable>;
